name: Update Blocklists

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install XML parsing tools
      run: sudo apt-get install -y xmlstarlet

    - name: Parse RSS Feed and Update domains.txt
      run: |
        curl -s 'https://palewi.re/docs/news-homepages/rss/sites/all.xml' | xmlstarlet sel -t -m "//item/link" -v . -n > domains.txt

    - name: Build Adguard blocklist
      run: sed -e 's/.*/||&^$important/' domains.txt > hosts_adguard.txt

    - name: Build Hosts file with 0.0.0.0
      run: sed -e 's/.*/0.0.0.0 &/' domains.txt > hosts_0.0.0.0.txt

    - name: Build Hosts file with 127.0.0.1
      run: sed -e 's/.*/127.0.0.1 &/' domains.txt > hosts_127.0.0.1.txt

    - name: Commit files
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Anirudh Sriram
        author_email: techwithanirudh@users.noreply.github.com
        message: "Updated blocklists"
        add: "*.txt"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
