name: Update All Blocklists

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-blocklists:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install CSV parsing tools
      run: sudo apt-get install -y csvkit

    - name: Download and Process CSV
      run: |
        curl -s 'https://raw.githubusercontent.com/palewire/news-homepages/main/newshomepages/sources/sites.csv' | csvcut -c url | tail -n +2 > domains.txt

    - name: Build Adguard blocklist
      run: sed -e 's/.*/||&^$important/' domains.txt > hosts_adguard.txt

    - name: Build Hosts file with 0.0.0.0
      run: sed -e 's/.*/0.0.0.0 &/' domains.txt > hosts_0.0.0.0.txt

    - name: Build Hosts file with 127.0.0.1
      run: sed -e 's/.*/127.0.0.1 &/' domains.txt > hosts_127.0.0.1.txt

    - name: Auto Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Updated blocklists"
        branch: "${{ github.ref }}"
        file_pattern: "*.txt"
        commit_user_name: "Blocklist Updater Bot"
        commit_user_email: "bots@techwithanirudh.com"
